phi2-dpo-M2_KL: # this should be the same as the name as the current directory
  prompt_template: "phi2-dpo-M2_KL/prompt.txt" # what prompt should be used for this model
  fn_completions: "huggingface_local_completions" # what function should be used to generate completions. See `src/alpaca_eval/decoders` for options
  completions_kwargs: # parameters to the completion function
    model_name: "Dudep/phi2-dpo-M2_KL"
    model_kwargs:
      torch_dtype: 'bfloat16'
      trust_remote_code: True
    max_new_tokens: 1024
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "phi2-dpo-M2_KL" # name in the leaderboard
  link: "https://huggingface.co/Dudep/phi2-dpo-M2_KL" # link to the model's repo/information in the leaderboard
